### ISSUE TITLE
Use of '@import' when modules are disabled

### ISSUE THREAD

**Issue by warpling** [mxcl/PromiseKit#224]
I'm having trouble getting **2.1.0** to build in **Xcode 6.4**. 

My project is all Objective-C. I have modules enabled in both the Project and Pods targets and my Podfile essentially looks like this (other pods removed). Builds were passing with 2.0.6, but I thought I might need to update to 2.1.0 to run in Xcode 7 and deploy to iOS 9. I'm not great at debugging these build system issues; fingers crossed that I'm not overlooking something simple…

![screen shot 2015-07-23 at 4 16 12 pm](https://cloud.githubusercontent.com/assets/220240/8864406/6b4039c0-3156-11e5-9c37-ebdc5be90e38.png)

````
# Uncomment this line to define a global platform for your project
platform :ios, "8.0"

# ignore all warnings from all pods
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

# Use Swift Frameworks
use_frameworks!

link_with 'MyApp', 'MyAppTests'

target 'MyApp' do
    pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git'
    pod 'PromiseKit/CoreLocation', :git => 'https://github.com/mxcl/PromiseKit.git'
end

````

**Comment by mxcl** [comment]
Can you provide the error messages?

**Comment by warpling** [comment]
The title is the only error I'm receiving. I took these screenshots after cleaning the build, deleting derived data, and rebuilding. The highlighted error is coming from line 64 in `PMKPromise.h`. As far as I can tell, modules are enabled in release/debug for all of my targets including Pods and PMKPromise's.

![screen shot 2015-07-23 at 11 05 00 pm](https://cloud.githubusercontent.com/assets/220240/8868614/6f8fb6b6-318f-11e5-949f-2e63cce7301b.png)

![screen shot 2015-07-23 at 11 05 23 pm](https://cloud.githubusercontent.com/assets/220240/8868612/6b84e26c-318f-11e5-99f6-f0d82129bee6.png)

**Comment by mxcl** [comment]
Your project has modules disabled. These are headers so they are included into your app's target and this is not CocoaPods related. Turn modules on in your app target.

**Comment by warpling** [comment]
I figured the same, but modules *are* turned on in all my targets (MyApp, MyAppTests, Pods (and each pod's target)). Is there somewhere other than build settings to enable modules?

**Comment by mxcl** [comment]
Edit the line and change it to:

```objc
#import <Foundation/NSDate.h>
```

Should fix it, if so, modules are disabled, somewhere anyway.

**Comment by mxcl** [comment]
I'm pushing 2.1.1 without the @import in a header so, hopefully that is all you need.

**Comment by warpling** [comment]
Now that you mention it, I remember this happening last time I updated (when I installed 2.0.6)! At that time I think I just made the fix by hand; updating to 2.1.0 must have overridden the change :)




Still, if modules are enabled, why might  this still throw off the compile?

**Comment by mxcl** [comment]
I don't know what specific build configuration is causing this problem, but it’s either modules related or a bug in the build systems.

**Comment by warpling** [comment]
Strange, I had to change a couple more `@import` instances, but it's good to know that that's all it takes to fix. Hopefully this issue helps anyone else with the same problem. Thanks for the help and library, Max :)

**Comment by mxcl** [comment]
Well, is it not all it took to fix it? I did a global search and the only place I found an `@import` in a header is there. You’re the tester here :)

**Comment by warpling** [comment]
Sorry that was extremely unclear. I meant that I had to replace all of *my* imports of PromiseKit:
````
//@import PromiseKit;
#import <PromiseKit/PromiseKit.h>
````

**Comment by mxcl** [comment]
Yes. You can't use `@import PromiseKit` with PromiseKit. This is documented in various places.

**Comment by warpling** [comment]
Gotcha, just found that note in the 2.0 release notes. Sorry I missed that when converting all my Pods to Frameworks.

**Comment by mxcl** [comment]
It's fine. I agree it's unexpected. It is done so Swift doesn't see the entire objective C interface as there would be conflicts.
