### ISSUE TITLE
Swift 4 Bugs - PromiseKit - Foundation & UIKit

### ISSUE THREAD

**Issue by Narsail** [mxcl/PromiseKit#707]
* PromiseKit version: 4.3.2
* Xcode version: 9 Beta 6
* CocoaPods version: 1.2.1

When using the new PromiseKit 4.3.2 with Swift 4 i got the following two Errors:

PromiseKit-Foundation:
afterlife.swift - line 23
```
Missing argument for parameter #1 in call
```

That's the one you fixed some days ago but it seems it isn't included in my project when using cocoa pods.

PromiseKit-UIKit
PMKAlertController.swift - 91
```
Contextual closure type '() -> Void' expects 0 arguments, but 1 was used in closure body 
Replace '_ -> Void in' with ''
```

Is there a way to exclude Extensions when fetching with Cocoapods? At the moment I doesn't use any extensions (although while searching this bugs I found some helpful extensions which I might use in the future ;))

**EDIT:**

I found a workaround - I started fetching PromiseKit with a arbitrary Subspec like:
```
pod "PromiseKit", "~> 4.3", :subspecs => ['WatchConnectivity',]
```
to not include the problematic extensions.

**Comment by mxcl** [comment]
Yes sorry, I am in the process of fixing all the extensions. As we speak even.

FYI: you can do this:

```
pod "PromiseKit", "~> 4.3", :subspecs => ['CorePromise']
```

**Comment by Narsail** [comment]
Ah that helps. Thanks for your fast response!

**Comment by mxcl** [comment]
Should be fixed with (the just released) 4.4.0

**Comment by mxcl** [comment]
LMK if this isn't fixed.

**Comment by nathan-inge** [comment]
PromiseKit Version: 4.5.0
Cocoapods Version: 1.2.1
Xcode Version: 9.2

@mxcl I am in the middle of migrating my project to Swift 4. 

Originally I was trying to do:

`pod 'PromiseKit/UIKit', '~> 4.5'`

But then tried (as per your suggestion):

`pod "PromiseKit", "~> 4.5", subspecs: ['CorePromise']`

However I am still getting just the two errors mentioned above:

`Missing argument for parameter #1 in call`

and 

`Contextual closure type '() -> Void' expects 0 arguments, but 1 was used in closure body `

Am I skipping over something or has this bug not been addressed in the UIKit extension?

**Comment by mxcl** [comment]
Please open a new ticket including files and line numbers. Thanks.
